accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path(
        'password-reset-done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
]

django_cve_2019_19844_poc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm


class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Don't use EmailInput. Because 'mıke@example.org' cannot be entered.
        self.fields['email'].widget = forms.TextInput()

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from .forms import PasswordResetForm


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'


class PasswordResetView(auth_views.PasswordResetView):
    form_class = PasswordResetForm
    subject_template_name = 'mails/password_reset/subject.txt'
    email_template_name = 'mails/password_reset/body.txt'
    template_name = 'password_reset.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'password_reset_confirm.html'


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'

accounts/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login</title>
</head>
<body>
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Login</button>
    <p><a href="{% url 'accounts:password_reset' %}">Password Reset</a></p>
  </form>
</body>
</html>

accounts/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Password Reset</title>
</head>
<body>
  <h1>Password Reset</h1>
  <form action="{% url 'accounts:password_reset' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Send</button>
  </form>
</body>
</html>

accounts/templates/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Password Reset Complete</title>
</head>
<body>
  <h1>Password Reset Complete</h1>
  <a href="{% url 'accounts:login' %}">Login</a>
</body>
</html>

accounts/templates/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Password Reset</title>
</head>
<body>
  <h1>Password Reset</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Reset</button>
  </form>
</body>
</html>

accounts/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Password Reset Done</title>
</head>
<body>
  <h1>Password Reset Done</h1>
</body>
</html>

accounts/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Profile</title>
</head>
<body>
  <h1>Hello, {{ request.user.username }}</h1>
  <a href="{% url 'accounts:logout' %}">Logout</a>
</body>
</html>